name: pocket_pal
description: gamified expense tracker.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^29.1.35
  sliding_up_panel: ^2.0.0+1
  lottie: ^3.3.1
  rive: ^0.12.0
  english_words: ^4.0.0
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  flutter_fortune_wheel: ^1.3.2
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/123.jpg
    - assets/animations/rocketttt.json
    - assets/animations/rockettttt.json
    - assets/animations/cosmos.riv
    - assets/logo.jpg
    - assets/coins.jpg
    - assets/box.jpg
    - assets/clover.png
    - assets/streak_freeze.webp
  uses-material-design: true
  fonts:
    - family: Arcade
      fonts:
        - asset: fonts/ARCADECLASSIC.TTF
    